### ISSUE TITLE
Add feedback form

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/tech-for-good-near-you#51]

**Comment by andrewMacmurray** [comment]
@eghale a link to the feedback form? I'm assuming we could do this as a google survey / form?

**Comment by eghale** [comment]
Yeah I wondered if there were any widgets that we could use so we don't have to take someone away from the page?

They only need to be able to write a line or two of feedback, and the text could just read something simple like 'This is currently in beta but we hope it's helpful. Please tell us what you think - all feedback and comments welcome!' @andrewMacmurray

**Comment by andrewMacmurray** [comment]
@eghale maybe we could try the one we use for the cast website, I don't think I can sign up for it though as you can only have one free one, do you recon you could make one on your account?

https://getsitecontrol.com/

**Comment by eghale** [comment]
Hmm have we had any responses to the one on the CAST website whatsoever? I think if not, it might not be the best option... It's also quite a big, intrusive pop-up, especially on mobile. Perhaps leave this one for now. Hard to know what best practice around collecting feedback on a beta site is!!
