### ISSUE TITLE
Add link to Google Sheet

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/tech-for-good-near-you#52]
Add Google sheet where all Tech for Good meetup groups are so that people visiting the website can add to it.

**Comment by ivan-unfolds** [comment]
@eghale Can you post the link on here?

**Comment by andrewMacmurray** [comment]
@eghale where would you like this to go on the site?

**Comment by eghale** [comment]
@ivanmauricio @andrewMacmurray  On the left-hand nav bar. Please could we move the spinning location button up above the 'events within' slider, then underneath the slider have a line that says 'Add your event to our Google Sheet' with Google Sheet hyperlinked to the spreadsheet.

If it's not too much extra work, please could you add the Summer of Tech for Good logo (below) and have that text read 'Add your [Summer of Tech for Good logo] event to our Google Sheet' instead, with the logo being hyperlinked to the sheet as well as the words? 

If this could be in the left-hand menu permanently like the top logo, not just once the results are delivered, that would be super :)

Shout if any questions! 

![techforgood_summer](https://user-images.githubusercontent.com/11066569/27644294-09b1a364-5c1b-11e7-873b-8177aa1278d4.jpg)

**Comment by andrewMacmurray** [comment]
Will mock this up tomorrow to see what it looks like. For mobile I'm assuming this can go in the top navbar when pressing the plus icon

**Comment by andrewMacmurray** [comment]
@eghale I can't seem to find the spreadsheet, could you put a link to it here?

**Comment by andrewMacmurray** [comment]
@eghale Thoughts on this?

![screen shot 2017-06-29 at 10 20 24](https://user-images.githubusercontent.com/14013616/27680713-9e1af80e-5cb4-11e7-8b02-3c03c331b4af.png)

**Comment by andrewMacmurray** [comment]
confirmed as good to go with this in meeting

**Comment by eghale** [comment]
Here's the link to the spreadsheet https://docs.google.com/spreadsheets/d/14ugF7_Vbad3FgZPs_fYhbW4EkVz_AK5NnsZ0TYXB_2o/edit#gid=1859950832

**Comment by andrewMacmurray** [comment]
closed with pr #74
