### ISSUE TITLE
Potential bug - map coordinates not correct

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/tech-for-good-near-you#57]
Just spotted this, which may be an unavoidable bug on Meetup's end (or the meetup organisers just entering the wrong address!), where the Dublin tech for good meetup is now apparently in the south of England... 

![screen shot 2017-06-20 at 10 50 31](https://user-images.githubusercontent.com/11066569/27327439-7f69d9da-55a6-11e7-9253-e5e63074f038.png)

No worries if there's nothing you can do, just thought I'd flag!

**Comment by andrewMacmurray** [comment]
@eghale will have a look at the data and see if there's any way of cleaning this up, not a huge amount we can do though if they've put bad data in at the source

**Comment by andrewMacmurray** [comment]
@eghale so it looks like that event only shows the location to members, maybe we could use the group lat lng as a fallback? Should at least appear in Dublin
