### ISSUE TITLE
Tech for Good Bath event not pulling through

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/tech-for-good-near-you#68]
@ivanmauricio @andrewMacmurray   This event isn't showing up, not sure why https://www.meetup.com/Tech4Good-Bath/events/239691699/

Please could you check this group is definitely on the list? https://www.meetup.com/Tech4Good-Bath/

I would fix this myself but I could find the Meetup API page that gives the group ID, or the part of the code where I should add new meetups by their ID directly (rather than adding it through the dashboard). Could you add instructions on how to do this to the ReadMe? :) Thanks!

**Comment by andrewMacmurray** [comment]
@eghale I don't think it's in the list, will add it. we might move the `group_ids` to a different place so won't add to the readme yet

**Comment by eghale** [comment]
Thanks :)

**Comment by andrewMacmurray** [comment]
closed with pr #74
