### ISSUE TITLE
Add 'Created by Andrew & Ivan at CAST' somewhere on the page

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/tech-for-good-near-you#73]
@andrewMacmurray  Not sure where this should go without it getting in the way of the beautiful simple layout, but if you can find somewhere to credit yourselves (and add a link to CAST) somewhere on here, that'd be fab :)

**Comment by andrewMacmurray** [comment]
we could try this in the bottom left on desktop, theres a bit in the mobile version in the top nav
"made with love at CAST" lol

**Comment by andrewMacmurray** [comment]
closed with pr #74
