### ISSUE TITLE
Formatting of 'Add to Google Sheet' needs fixing upon postcode submission

### ISSUE THREAD

**Issue by eghale** [TechforgoodCAST/tech-for-good-near-you#76]
Looks great before I submit the postcode, but once I'm looking at the event list, the left bar gets a bit overlapped with the distance slider:

![screen shot 2017-07-03 at 16 20 40](https://user-images.githubusercontent.com/11066569/27799200-2f10acfa-600c-11e7-98b6-60060cfe852f.png)

@andrewMacmurray @ivanmauricio

**Comment by andrewMacmurray** [comment]
@eghale I've been messing around with the layout and it seems like hiding the logo when the height is too small is the best solution, everything gets way too small, squished and unreadable otherwise
