### ISSUE TITLE
Switch maps to leaflet

### ISSUE THREAD

**Issue by drkane** [TechforgoodCAST/tech-for-good-near-you#88]
http://leafletjs.com/

**Comment by andrewMacmurray** [comment]
After playing around with leaflet for a bit with the new changes, I've decided we're going to stick with google maps for now, it's not offering anything significantly better than google maps and the new quirks it was introducing were becoming a blocker for little payoff.

However, it's most likely that when this package: https://github.com/klaftertief/slippery-slope is released we'll transition over to it using leaflet internally.
